PortaFolio_JERH/Models/CMT_TodoModel.cs
using System.Reflection;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace PortaFolio_JERH.Models
{
    public class CMT_TodoModel
    {

        public string DaPe_Nombres { get; set; }
        public string DaPe_ApePa { get; set; }
        public string DaPe_ApeMa { get; set; }
        public string DaPe_Numero_cel { get; set; }
        public string DaPe_Correo1 { get; set; }
        public string DaPe_Correo2 { get; set; }
        public string DaPe_Sobremi { get; set; }
        public string DaPe_Intereses { get; set; }
        public string DaPe_Perfil { get; set; }
        public string Tec_Lenguaje { get; set; }
        public int Tec_Nivel { get; set; }
        public string Dic_Calle { get; set; }
        public int Dic_NumeroDeCasa { get; set; }
        public string Dic_Coloniea { get; set; }
        public string Dic_CalleTrasera { get; set; }
        public string Dic_Ciudad { get; set; }
        public string Dic_Estad { get; set; }
      

    }
}

PortaFolio_JERH/Models/ErrorViewModel.cs
namespace PortaFolio_JERH.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PortaFolio_JERH/Models/MessageViewModel.cs
namespace PortaFolio_JERH.Models
{
    public class MessageViewModel
    {
        public string Numero { get; set; }
        public string Message { get; set; }
    }
}

PortaFolio_JERH/Controllers/DatosPersonalesController.cs
using PortaFolio_JERH.Models;
using PortaFolio_JERH.Datos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Twilio;
using Twilio.Rest.Api.V2010.Account;

namespace PortaFolio_JERH.Controllers
{
    public class DatosPersonalesController : Controller
    {
        private readonly IConfiguration _configuration;

        DaPersonalesDatos _Datos = new DaPersonalesDatos();

        public IActionResult Index()
        {
            var lista = _Datos.Listar();
            return View(lista);
        }
        public DatosPersonalesController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Mensage()
        {
            return View(new MessageViewModel());
        }

        [HttpPost]
        public IActionResult SendSms(MessageViewModel model)
        {
            if (ModelState.IsValid)
            {
                var accountSid = _configuration["Twilio:AccountSid"];
                var authToken = _configuration["Twilio:AuthToken"];

                TwilioClient.Init(accountSid, authToken);

                var messageResource = MessageResource.Create(
                    body: model.Message,
                    // Reemplaza con tu número de Twilio, en este caso, "+1 256 661 4023"
                    from: new Twilio.Types.PhoneNumber("+12566614023"),
                    to: new Twilio.Types.PhoneNumber(model.Numero)
                );

                // Puedes agregar un mensaje de éxito o manejar redireccionamientos según tus necesidades.
                ViewBag.SuccessMessage = "Mensaje enviado con éxito.";
            }
            else
                ViewBag.SuccessMessage = "Algo salio mal.";

            return View("Index", model);
        }
       public IActionResult Proyectos()
        {
            var lista = _Datos.Listar();
            return View(lista);
        }
    }
}

PortaFolio_JERH/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PortaFolio_JERH.Models;
using System.Diagnostics;

namespace PortaFolio_JERH.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PortaFolio_JERH/Views/DatosPersonales/Index.cshtml
@model List<CMT_TodoModel>;


@{
    ViewData["Title"] = "Listar";
    Layout = "_Layout";
}
<section class="inicio" id="inicio">
    <div class="contenido-seccion">
        <header>
            <div class="nav-bar" onclick="mostrarOcultarMenu()">
                <i class="fa-solid fa-bars"></i>
            </div>
            <!--
            <nav id="nav" class="nav">
                <a href="#inicio">Inicio</a>
                <a href="#sobremi">Sobre mí</a>
                <a href="#habilidades">Habilidades</a>
                <a href="#resumen">Resumen</a>
                <a href="#contacto">Contacto</a>
            </nav>
            -->

            <div class="logo">
                M<span class="color">S</span>
            </div>
        </header>
        <div class="info">
            <!--Aqui va mi nombre-->
            <h1>
                @for (int item = 0; item < 1; item++)
                {
                    var currentItem = Model[item];
                    <p>@currentItem.DaPe_Nombres @currentItem.DaPe_ApePa @currentItem.DaPe_ApeMa</p>
                }
            </h1>

            <h2>Estudiante de la carrera de Tecnologías de la <br>Información, área Desarrollo de Software Multiplataforma </h2>
            <div class="redes">
                <a href="https://www.facebook.com/jesuseloyr/"><i class="fa-brands fa-facebook-f"></i></a>
                <a href="https://www.instagram.com/th3.j3rh/"><i class="fa-brands fa-square-instagram"></i></a>
                <a href="https://github.com/jerh011"><i class="fa-brands fa-square-github"></i></a>
                <a href="https://wa.me/526221443188"><i class="fa-brands fa-whatsapp"></i></a>

            </div>
        </div>
        <div class="foto">
            <img src="/css/Portada.jpg" alt="">
        </div>
    </div>
</section>

<!-- SECCION SOBRE MI -->
<section class="sobremi" id="sobremi">
    <div class="contenido-seccion">
        <h2 class="titulo-seccion">Sobre Mi</h2>
        <h3>Detalles personales</h3>

        <p class="especial">Me dedico a producir ideas creativas y originales para mis clientes</p>
     
        @for (int item = 0; item < 1; item++)
        {
            var currentItem = Model[item];
            <p>@currentItem.DaPe_Sobremi</p>
        }

        <div class="fila">
            <div class="col">
                <i class="fa-solid fa-user"></i>
                <span class="titulo-detalle">Perfil</span>
                
                @for (int item = 0; item < 1; item++)//falta un campo en base de datos sobre perfil
                {
                    var currentItem = Model[item];
                    <p>@currentItem.DaPe_Perfil</p>
                }

            </div>
            <div class="col">
                <i class="fa-solid fa-location-pin"></i>
                <span class="titulo-detalle">Ubicación</span>
                @for (int item = 0; item < 1; item++)//Ubicacion
                {
                    var currentItem = Model[item];
                    <p>
                        <b>Colonia:</b> @currentItem.Dic_Coloniea<br>
                        <b>Calle:</b> @currentItem.Dic_Calle<br>
                        <b>Numero:</b> #@currentItem.Dic_NumeroDeCasa<br>
                        <b>Calletrasera:</b> @currentItem.Dic_CalleTrasera<br>
                        <b>Ciudad:</b> @currentItem.Dic_Ciudad<br>
                        <b>Estado:</b> @currentItem.Dic_Estad<br>

                    </p>
                }
             </div>
            <div class="col">
                <i class="fa-solid fa-flag"></i>
                <span class="titulo-detalle">Intereses</span>
                @for (int item = 0; item < 1; item++)//falta un campo en base de datos sobre perfil
                {
                    var currentItem = Model[item];
                    <p>@currentItem.DaPe_Intereses</p>
                }
            
            </div>
        </div>
    </div>
</section>



<!--Habilidades -->
<section>
    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button Fondo" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Habilidades
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class=" Trasparente accordion-body">
                    <!--Aque va el codigo -->
                    <div class="habilidades" id="Habilidades">

                        <div class="row">
                            @foreach (var item in Model)
                            {
                                <div class="col-sm-12 col-md-6 col-lg-4">
                                    <h2>@item.Tec_Lenguaje </h2>
                                    <div class="Barra">
                                        <div class="html" style="width:@item.Tec_Nivel%; animation: html 3s;"></div>
                                    </div>@item.Tec_Nivel%
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!---->
     </div>
</section>

<br><br><br>

PortaFolio_JERH/Views/DatosPersonales/Mensage.cshtml
@model PortaFolio_JERH.Models.MessageViewModel

<h2 style="color:white">Enviar Mensaje de Texto</h2>

<form asp-controller="Home" asp-action="SendSms" method="post">
    <div class="form-group">
        <label for="to" style="color:white">Número de Destino:</label>
        <input type="text" class="form-control" id="to" name="to" placeholder="Ejemplo: +1234567890" required>
    </div>
    <div class="form-group">
        <label for="message" style="color:white">Mensaje:</label>
        <textarea class="form-control" id="mensaje" name="message" rows="10" placeholder="Escribe tu mensaje aquí" required></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Enviar Mensaje</button>
</form>
<br>
<br>
<br>

PortaFolio_JERH/Views/DatosPersonales/Proyectos.cshtml
@model List<CMT_TodoModel>;


@{
    ViewData["Title"] = "Listar";
    Layout = "_Layout";
}
<center><h2 style="color:white">CALCULADORA</h2></center>
<br>
<section>
<div id="carouselExampleCaptions" class="carousel slide">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4" aria-label="Slide 5"></button>
    </div>
    <div class="carousel-inner">
        
        <div class="carousel-item active">
            <img src="/css/Calculadora_1.jpg" class="d-block w-100" alt="es la primera pantalla la calculadora" width="1000" height="1000">
            <div class="carousel-caption d-none d-md-block">
                <h5>Consistia en recrear la calculadora de nuestos celulares</h5>
                <p>Se utilizo xamarin. Para fron se utilizo XML y como Back C#  </p>
            </div>
        </div>

        <div class="carousel-item">
            <img src="/css/Calculadora_2.jpg" class="d-block w-100" alt="" width="1000" height="1000">
            <div class="carousel-caption d-none d-md-block">
                    <h5>Consistia en recrear la calculadora de nuestos celulares</h5>
                    <p>Se utilizo xamarin. Para fron se utilizo XML y como Back C#  </p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="/css/Calculadora_3.jpg" class="d-block w-100" alt="" width="1000" height="1000">
            <div class="carousel-caption d-none d-md-block">
                    <h5>Consistia en recrear la calculadora de nuestos celulares</h5>
                    <p>Se utilizo xamarin. Para fron se utilizo XML y como Back C#  </p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="/css/Calculadora_4.jpg" class="d-block w-100" alt="" width="1000" height="1000">
            <div class="carousel-caption d-none d-md-block">
                    <h5>Consistia en recrear la calculadora de nuestos celulares</h5>
                    <p>Se utilizo xamarin. Para fron se utilizo XML y como Back C#  </p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="/css/Calculadora_5.jpg" class="d-block w-100" alt="" width="1000" height="1000">
            <div class="carousel-caption d-none d-md-block">
                    <h5>Consistia en recrear la calculadora de nuestos celulares</h5>
                    <p>Se utilizo xamarin. Para fron se utilizo XML y como Back C#  </p>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
</section>
<br><br>
<!-------Biblioteca VIRTUAL--------------->
<br>
<br>
<center><h2 style="color:white">Biblioteca virtual</h2></center>
<br>
<section>

    <div id="carouselExampleDark" class="carousel carousel-dark slide">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="3" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="4" aria-label="Slide 4"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="5" aria-label="Slide 5"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="6" aria-label="Slide 6"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="7" aria-label="Slide 7"></button>
        </div>
        <div class="carousel-inner">

            <div class="carousel-item active">
                <img src="/css/Biblioteca_1.png" class="d-block w-100" alt="es la primera pantalla la calculadora" width="1000" height="1000">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="color:white">Login de biblioteca</h5>
                    <p style="color:white">Solamente como front se uso un poco de HTML , CSS y BOOTSTRAP, como back C# con una arquitectura MVC y conecion de datos a SQL SERVER  </p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="/css/Biblioteca_2.png" class="d-block w-100" alt="" width="1000" height="1000">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="color:white">Login de biblioteca</h5>
                    <p style="color:white">Solamente se uso un poco de HTML , CSS y BOOTSTRAP </p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="/css/Biblioteca_3.png" class="d-block w-100" alt="" width="1000" height="1000">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="color:white">Crud de Libros</h5>
                    <p style="color:white">Como front se uso un poco de HTML , CSS y BOOTSTRAP, como back C# con una arquitectura MV, conecion de datos a SQL SERVER y muestra todos lo libros registrados.  </p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="/css/Biblioteca_4.png" class="d-block w-100" alt="" width="1000" height="1000">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="color:white">Crud de Usuarios</h5>
                    <p style="color:white">Como front se uso un poco de HTML , CSS y BOOTSTRAP, como back C# con una arquitectura MV, conecion de datos a SQL SERVER, muestra todos lo usuarios registrados y la contraseña salia ecriptada para que alguien malicioso no peda acceder tan fasilmente a los datos de usuario.  </p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="/css/Biblioteca_5.png" class="d-block w-100" alt="" width="1000" height="1000">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="color:white">Crud de Prestamo</h5>
                    <p style="color:white">Como front se uso un poco de HTML , CSS y BOOTSTRAP, como back C# con una arquitectura MV, conecion de datos a SQL SERVER y muestra todos lo prestamo de los libros asi como los usuiarios a los que se les fue confiado los libros.  </p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="/css/Biblioteca_6.png" class="d-block w-100" alt="" width="1000" height="1000">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="color:white">Registros</h5>
                    <p style="color:white">Como front se uso un poco de HTML , CSS y BOOTSTRAP, como back C# con una arquitectura MV, conecion de datos a SQL SERVER e ingresa el registro de la base de datos en este caso libros pero para el resto de los crud son muy similares.  </p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="/css/Biblioteca_7.png" class="d-block w-100" alt="" width="1000" height="1000">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="color:white">Edicion</h5>
                    <p style="color:white">Como front se uso un poco de HTML , CSS y BOOTSTRAP, como back C# con una arquitectura MV, conecion de datos a SQL SERVER y edita el registro de la base de datos en este caso libros pero para el resto de los crud son muy similares.  </p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="/css/Biblioteca_8.png" class="d-block w-100" alt="" width="1000" height="1000">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="color:white">Edicion</h5>
                    <p style="color:white">Como front se uso un poco de HTML , CSS y BOOTSTRAP, como back C# con una arquitectura MV, conecion de datos a SQL SERVER y elimina el registro de la base de datos en este caso libros pero para el resto de los crud son muy similares.  </p>

                </div>
            </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

</section>



<br>
<br>
<br>

PortaFolio_JERH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PortaFolio_JERH</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PortaFolio_JERH.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="DatosPersonales" asp-action="Index">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DatosPersonales" asp-action="Mensage">Contacta por mensage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DatosPersonales" asp-action="Proyectos">Proyectos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="blockquote-footer border-top footer text-muted ">
        <div class="container">
            &copy; 2023 - PortaFolio_JERH - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>